ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino

# Arduino Uno
BOARD_TAG = uno

# Arduino Nano
#BOARD_TAG = nano328

# most likely different on your machine
MONITOR_PORT = /dev/ttyACM0

CXXFLAGS_STD = -std=gnu++11
CFLAGS_STD = -std=gnu11

ARDUINO_LIBS = RF24L01

include ${ARDMK_DIR}/Arduino.mk
